apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
  labels:
    app: java
spec:
  replicas: 6
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollungUpdate
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
   sec:
    containers:
    - name: java
      #image: <account-id>.dkr.ecr.<region>.amazonaws.com/<repository-name>:<tag>
      image: 453229563354.dkr.ecr.us-west-2.amazonaws.com/java-application:10
      ports:
 - containerPort: 8080

---
apiVersion: v1
kind: service
metadata:
  name: java-app-services
  labels:
    app: java
spec:
  selector:
    app: java
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
